#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIST_DIR="${SCRIPT_DIR}/../dist"
PROJECT_DIR="${SCRIPT_DIR}/../"

# build project javascript
npm run build
cp -v "${DIST_DIR}/website/main.js" "${PROJECT_DIR}/docs/front-main.js"

# build art index
cd "${PROJECT_DIR}/docs"
ls -d art-* > art-index.txt
